add_newline = true
command_timeout = 1000
format = "$directory$git_branch$git_state$git_status$line_break$character"

[character]
error_symbol = "[↪ ](red)"
success_symbol = "[↪ ](red)"
vimcmd_symbol = "[↪ ](green)"

[directory]
style = "blue"

[git_branch]
format = "[$branch]($style)"
style = "bright-black"

[git_status]
conflicted = "​"
deleted = "​"
format = "[[(*$conflicted$untracked$modified$staged$renamed$deleted)](218) ($ahead_behind$stashed)]($style)"
modified = "​"
renamed = "​"
staged = "​"
stashed = "≡"
style = "cyan"
untracked = "​"

[git_state]
format = '\([$state( $progress_current/$progress_total)]($style)\) '
style = "bright-black"

[hostname]
disabled = false
